# Generated by Django 3.1.6 on 2021-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.CharField(choices=[('ALGO', 'Algorithm'), ('JVSC', 'Javascript'), ('HTML', 'HTML(CSS)'), ('JAVA', 'Java'), ('CLNG', 'C'), ('CPSC', 'ComScience'), ('PROJ', 'Project'), ('DATA', 'Data(DB)'), ('PYTH', 'Python')], max_length=80, null=True)),
                ('title', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('subtitle1', models.CharField(max_length=50)),
                ('subimg1', models.ImageField(blank=True, null=True, upload_to='')),
                ('subcontents1', models.TextField()),
                ('subtitle2', models.CharField(max_length=50)),
                ('subimg2', models.ImageField(blank=True, null=True, upload_to='')),
                ('subcontents2', models.TextField()),
                ('subtitle3', models.CharField(max_length=50)),
                ('subimg3', models.ImageField(blank=True, null=True, upload_to='')),
                ('subcontents3', models.TextField()),
                ('conclusiontitle', models.CharField(max_length=50)),
                ('conclusionimg', models.ImageField(blank=True, null=True, upload_to='')),
                ('conclusioncontents', models.TextField()),
            ],
        ),
    ]
