# Generated by Django 3.1.6 on 2021-02-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210215_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorys',
            field=models.CharField(choices=[('HTML', 'HTML(CSS)'), ('ALGO', 'Algorithm'), ('JVSC', 'Javascript'), ('PROJ', 'Project'), ('JAVA', 'Java'), ('PYTH', 'Python'), ('DATA', 'Data(DB)'), ('CPSC', 'ComScience'), ('CLNG', 'C')], max_length=80, null=True),
        ),
    ]
