# Generated by Django 3.1.6 on 2021-02-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210218_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorys',
            field=models.CharField(choices=[('JVSC', 'Javascript'), ('ALGO', 'Algorithm'), ('DATA', 'Data(DB)'), ('JAVA', 'Java'), ('PYTH', 'Python'), ('CLNG', 'C'), ('PROJ', 'Project'), ('CPSC', 'ComScience'), ('HTML', 'HTML(CSS)')], max_length=80, null=True),
        ),
    ]
