# Generated by Django 3.1.6 on 2021-02-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210218_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorys',
            field=models.CharField(choices=[('DATA', 'Data(DB)'), ('ALGO', 'Algorithm'), ('CPSC', 'ComScience'), ('CLNG', 'C'), ('PYTH', 'Python'), ('HTML', 'HTML(CSS)'), ('PROJ', 'Project'), ('JAVA', 'Java'), ('JVSC', 'Javascript')], max_length=80, null=True),
        ),
    ]
